services:
  auth-service:
    image: ghcr.io/mathiaslopez/auth-service:latest
    container_name: auth-service
    ports:
      - "${AUTH_PORT:-3000}:3000"
    restart: "always"
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      - APP_NAME=${APP_NAME}  
      - MAIL_SENDER=${MAIL_SENDER}
      - AUTH_URL=${AUTH_URL}
      - MAILTRAP_TOKEN=${MAILTRAP_TOKEN}
      - JWT_EMAIL_VERIFICATION_SECRET=${JWT_EMAIL_VERIFICATION_SECRET}
      - JWT_EMAIL_VERIFICATION_EXPIRATION=${JWT_EMAIL_VERIFICATION_EXPIRATION}
      - NODE_ENV=${NODE_ENV}
      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_AUTH_EXPIRATION=${JWT_AUTH_EXPIRATION}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - COOKIE_SHARING_KEY=${COOKIE_SHARING_KEY}
      - ALLOWED_ORIGIN_PATTERN=${ALLOWED_ORIGIN_PATTERN}
      - DATABASE_URL=${DATABASE_URL}
  
  auth-db:
    image: postgres:17
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: